server:
  port: 8888

spring:
  application:
    name: configserver-spring
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenism/configserverrepo-spring
      monitor:
        github:
          enabled: true
          
logging:
  level:
    org.springframework.cloud: 'DEBUG'          